CREATE TABLE USUARIO(
	LOGIN VARCHAR2(100),
	CONTRASENNA VARCHAR(100),
	SALDO NUMBER(10, 2),
	PREMIUM NUMBER(1),
	CONSTRAINT PK_USUARIO PRIMARY KEY(LOGIN)
);

CREATE TABLE BILLETES(
	LOGIN VARCHAR2(9),
	DNI VARCHAR2(9),
	FECHA_COMPRA DATE,
	FECHA_SALIDA DATE,
	FECHA_VUELTA DATE,
	NOMBRE_AEROLINEA VARCHAR2(100),
	TIPO_BILLETE VARCHAR2(50),
	CONSTRAINT PK_BILLETES PRIMARY KEY(FECHA_COMPRA),
	CONSTRAINT FK_LOGIN FOREIGN KEY (LOGIN) REFERENCES USUARIO(LOGIN)
);
